<?php
/**
 * User: isliang
 * Date: 2019-09-13
 * Time: 14:45
 * Email: yesuhuangsi@163.com
 **/

namespace Ipf\Constant;

class ExceptionConst
{
    const CODE_CONFIG_PATH_UNDEFINED = 10001;

    const CODE_CLASS_NOT_FOUND = 10002;

    const CODE_METHOD_NOT_FOUND = 10003;

    const CODE_ROUTE_NOT_FOUND = 10004;

    const CODE_REQUEST_METHOD_NOT_ALLOWED = 10005;

    const CODE_ROUTE_CONFIG_NOT_FOUND = 10006;

    const CODE_LOG_CONFIG_NOT_FOUND = 10007;

    const CODE_ROUTE_CONFIG_FORMAT_ERROR = 10008;

    const CODE_LOG_CONFIG_FORMAT_ERROR = 10009;

    const CODE_PDO_CONFIG_NOT_FOUND = 10010;

    const CODE_PDO_CONFIG_FORMAT_ERROR = 10011;

    const CODE_MYSQL_CONFIG_NOT_FOUND = 10012;

    const CODE_MYSQL_CONFIG_FORMAT_ERROR = 10013;

    const CODE_MYSQL_NO_USABLE_CONNECTION_ERROR = 10014;

    const CODE_REDIS_CONFIG_NOT_FOUND = 10015;

    const CODE_REDIS_CONFIG_FORMAT_ERROR = 10016;

    const CODE_REDIS_NO_USABLE_CONNECTION_ERROR = 10017;

    const CODE_MEMCACHED_CONFIG_NOT_FOUND = 10018;

    const CODE_MEMCACHED_CONFIG_FORMAT_ERROR = 10019;

    const CODE_MYSQL_SERVER_OFFLINE = 2006;

    const CODE_LOST_CONNECTION_TO_MYSQL_SERVER = 2013;
}
